'use client'

import { useState, useEffect } from 'react'
import { Card } from "@/components/ui/Card"
import { Badge } from "@/components/ui/Badge"
import { Button } from "@/components/ui/Button"
import { createClient } from "@/lib/supabase/client"
import Link from 'next/link'

export default function TasksPage() {
  const [groupedTasks, setGroupedTasks] = useState({})
  const [loading, setLoading] = useState(true)
  const [openWorkflowId, setOpenWorkflowId] = useState(null)
  
  const supabase = createClient()

  useEffect(() => {
    fetchTasks()
  }, [])

  async function fetchTasks() {
    setLoading(true)
    const { data: { user } } = await supabase.auth.getUser()

    if (!user) {
      setLoading(false)
      return
    }

    // Ambil data task dan inner join ke workflows
    const { data, error } = await supabase
      .from('tasks')
      .select(`
        *,
        workflows!inner ( tittle, user_id )
      `)
      .eq('workflows.user_id', user.id)
      .order('created_at', { ascending: false })

    if (error) {
      console.error(error)
      setLoading(false)
      return
    }

    // Kelompokkan Task berdasarkan Workflow
    const grouped = data.reduce((acc, task) => {
       const wId = task.workflow_id
       if (!acc[wId]) {
           acc[wId] = {
               workflow_id: wId,
               workflow_tittle: task.workflows?.tittle || 'Deleted Workflow',
               tasks: []
           }
       }
       acc[wId].tasks.push(task)
       return acc
    }, {})

    setGroupedTasks(grouped)
    setLoading(false)
  }

  async function handleMarkStatus(taskId, status) {
    const { error } = await supabase
      .from('tasks')
      .update({ status })
      .eq('id', taskId)

    if (!error) {
      fetchTasks() // Refresh data grouping
    }
  }

  async function handleDelete(id) {
    if (!confirm('Are you sure you want to delete this task?')) return
    const { error } = await supabase.from('tasks').delete().eq('id', id)
    if (!error) {
      fetchTasks()
    }
  }

  if (loading) {
    return <div className="flex justify-center p-20"><span className="spinner border-purple-500 w-10 h-10"></span></div>
  }

  const groupArray = Object.values(groupedTasks)

  return (
    <div className="space-y-8 animate-fade-in max-w-5xl mx-auto">
      <div>
        <h1 className="text-3xl font-bold tracking-tight mb-2">Grouped Tasks</h1>
        <p className="text-gray-400">Manual interventions and approvals generated by AI, sorted by Workflow.</p>
      </div>

      {groupArray.length === 0 ? (
        <Card className="flex flex-col items-center justify-center p-12 text-center border-[#272737]">
          <div className="w-16 h-16 rounded-full bg-emerald-500/10 flex items-center justify-center mb-4 text-emerald-500">
            <svg className="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" /></svg>
          </div>
          <h2 className="text-xl font-bold mb-2">All Caught Up!</h2>
          <p className="text-gray-400 max-w-sm">There are no pending tasks waiting for your approval. Generate a new workflow to start automating.</p>
        </Card>
      ) : (
        <div className="space-y-4">
           {groupArray.map(group => {
               const isOpen = openWorkflowId === group.workflow_id
               const total = group.tasks.length
               const completed = group.tasks.filter(t => t.status === 'done').length

               return (
                 <Card key={group.workflow_id} className="p-0 border-[#272737] overflow-hidden group">
                     {/* Workflow Header (Clickable) */}
                     <div 
                       className="p-5 flex justify-between items-center bg-[#16161e] cursor-pointer hover:bg-white/5 transition-colors"
                       onClick={() => setOpenWorkflowId(isOpen ? null : group.workflow_id)}
                     >
                         <div className="flex-1">
                            <h2 className="text-xl font-bold text-white group-hover:text-purple-400 transition-colors flex items-center">
                               {group.workflow_tittle}
                            </h2>
                            <p className="text-sm text-gray-500 mt-1 uppercase tracking-wider font-bold">
                               {total} Tasks <span className="mx-2">•</span> {completed} Completed
                            </p>
                         </div>
                         <div className="flex items-center gap-4">
                            {completed === total ? (
                               <Badge status="done" className="bg-emerald-500/20 text-emerald-400 border-none">ALL DONE</Badge>
                            ) : (
                               <Badge status="todo" className="bg-purple-500/20 text-purple-400 border-none">PENDING</Badge>
                            )}
                            <div className={`p-2 rounded bg-[#0f0f14] border border-[#272737] transition-transform duration-300 ${isOpen ? 'rotate-180' : ''}`}>
                               <svg className="w-5 h-5 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" /></svg>
                            </div>
                         </div>
                     </div>
                     
                     {/* Tasks List Dropdown */}
                     {isOpen && (
                         <div className="p-6 border-t border-[#272737] bg-black/30 animate-fade-in shadow-inner">
                            <ul className="space-y-3">
                               {group.tasks.map((t, idx) => (
                                  <li key={t.id} className="flex flex-col sm:flex-row sm:items-center justify-between p-4 rounded-xl bg-[#0f0f14] border border-[#272737] hover:border-purple-500/30 transition-colors">
                                     <div className="flex items-start gap-4 mb-4 sm:mb-0">
                                        <div className="w-8 h-8 rounded shrink-0 bg-[#1e1e2a] text-gray-400 flex items-center justify-center font-bold font-mono text-sm border border-[#272737]">
                                          {idx + 1}
                                        </div>
                                        <div>
                                          <h3 className={`font-medium ${t.status === 'done' ? 'text-gray-500 line-through' : 'text-white'}`}>
                                            {t.tittle}
                                          </h3>
                                          <div className="flex items-center gap-2 mt-1">
                                             <span className="text-xs text-gray-600">{new Date(t.created_at).toLocaleDateString()}</span>
                                          </div>
                                        </div>
                                     </div>
                                     
                                     <div className="flex items-center gap-2 self-end sm:self-center ml-12 sm:ml-0">
                                        <Badge status={t.status}>{t.status}</Badge>
                                        {t.status !== 'done' ? (
                                           <button 
                                             onClick={() => handleMarkStatus(t.id, 'done')}
                                             className="text-xs px-3 py-1.5 rounded-lg bg-emerald-500/10 hover:bg-emerald-500/30 text-emerald-500 transition-colors border border-emerald-500/20"
                                           >
                                             Mark Done
                                           </button>
                                        ) : (
                                           <button 
                                             onClick={() => handleMarkStatus(t.id, 'todo')}
                                             className="text-xs px-3 py-1.5 rounded-lg bg-gray-500/10 hover:bg-gray-500/30 text-gray-400 transition-colors border border-gray-500/20"
                                           >
                                             Undo
                                           </button>
                                        )}
                                        <button 
                                          onClick={() => handleDelete(t.id)}
                                          className="p-1.5 rounded-lg bg-red-500/10 hover:bg-red-500/30 text-red-500 transition-colors border border-red-500/20 ml-2"
                                        >
                                           <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" /></svg>
                                        </button>
                                     </div>
                                  </li>
                               ))}
                            </ul>
                            
                            <div className="mt-4 pt-4 border-t border-[#272737] flex justify-end">
                               <Link href={`/workflows/${group.workflow_id}`}>
                                  <Button variant="ghost" className="text-sm">View Full Architecture</Button>
                               </Link>
                            </div>
                         </div>
                     )}
                 </Card>
               )
           })}
        </div>
      )}
    </div>
  )
}
